print("Setting up Python")
print("Download Python: Link")
print("Installation steps with screenshots")
print("Ensure checkboxes are marked and click Install Now.")
print("We can also use Replit")
print("Replit is virtual environment used to bulid software fastly")
print("Can create files based on the requirements with the templates available")
print("Can create HTML,Python.. etc using Replit")
print("The activity link is to be Fork it into replit for the further process")
